spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cprdb
    username: bear
    password: grylls
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        show-sql: true